### ISSUE TITLE
Change the default api-secret name to empty

### ISSUE THREAD

**Issue by pgoldtho** [visulate/visulate-for-oracle#105]
Change the manifest to include the word "empty" in its name
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-js
type: Opaque
stringData:
  database.js: |-
{{ .Files.Get "database.js" | indent 4 }}
```
