### ISSUE TITLE
Requests to the API server fail with a 502 if a database host becomes unavailable

### ISSUE THREAD

**Issue by pgoldtho** [visulate/visulate-for-oracle#139]
The API server handles errors if a database connection is unreachable during startup. It fails with a 502 if the database host becomes unreachable after the connection pool has been established.

Workaround is to restart the deployment.  E.g.

```
kubectl scale deployment visulate-1-visulate-api --replicas=0
kubectl scale deployment visulate-1-visulate-api --replicas=2
```

**Comment by pgoldtho** [comment]
The issue only occurs if the host becomes unreachable. It does not occur if a database is shutdown after the connection pool is established.

**Comment by pgoldtho** [comment]
Fix pushed in #141 was closing valid connections.

**Comment by pgoldtho** [comment]
Fixed the issue in a test environment using sqlnet.ora parameters - see https://github.com/oracle/node-oracledb/issues/1274

**Comment by pgoldtho** [comment]
Issue resolved. #144 removed promise timeouts and added  `SQLNET.RECV_TIMEOUT=3` to sqlnet.ora. Also changed API deployment readiness probe to a liveness probe and increased the period and timeout values: 
```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /endpoints/
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 20
```
This triggers a pod restart if more than 3 /endpoint calls timeout. The connection pools are recreated on startup. The unreachable host connection pool(s) are not created.
